### ISSUE TITLE
Self generating plugins via prompt.

### ISSUE THREAD

**Issue by Wladastic** [Significant-Gravitas/Auto-GPT-Plugins#1]
Create a UI prompt that auto-gpt interprets and creates a plugin with.

ex.: role: you are auto-gpt, you improve yourself according to a prompt given by the user

goals:
- read prompt and interpret 5 goals and a role out of it for auto-gpt
- write extended notes about the prompt and review the notes regularly
- assure auto-gpt builds a plugin that solves the prompt
- sketch a python script test.py before researching anything
- every 3 steps review the test.py and improve it

**Comment by ntindle** [comment]
Could be fun, closing as not a plugin for now!
