### ISSUE TITLE
PDF Reader integration for Auto-GPT

### ISSUE THREAD

**Issue by ajmtrz** [Significant-Gravitas/Auto-GPT-Plugins#100]
Hello devs, I have created a plugin for Auto-GPT that allows it to read PDF files 5b8c3c918ed5083c30fd492127542ac145224adb. The problem I have encountered is that if the PDF is too long, Auto-GPT displays the following error: 
`CRITICISM:  I need to ensure that the algorithm I use to summarize the text is appropriate and produces a concise and accurate summary. I also need to make sure that I handle any exceptions that may arise during the process.`
`NEXT ACTION:  COMMAND = read_pdf ARGUMENTS = {'pdf_url': 'http://web.seducoahuila.gob.mx/biblioweb/upload/Garcia%20Marquez%20Gabriel%20-%20Ojos%20De%20Perro%20Azul.PDF'}`
`SYSTEM:  Failure: command read_pdf returned too much output. Do not execute this command again with the same arguments.`
I am writing to ask for your help, and I would be grateful for your collaboration. Perhaps it is necessary to chunk the PDF and create embeddings in OpenAI and save the vector in the memory backend. I say this because of the little research I have done on the web, and I also wouldn't know how to do it. That's why I'm asking for your help. I send my greetings to all of you.

**Comment by ntindle** [comment]
Thanks! this is a workaround for a known bug to prevent the whole thing from crashing @Pwuts is working on a better fix (I think)

**Comment by ajmtrz** [comment]
Hello @ntindle , thanks for your reply. I have used the library `autogpt.processing.text` to add the mentioned functionality. Now, Auto-GPT is capable of reading any PDF file from any source. This is the commit 94f029c02cff33bade68d51ce5158d593696d2de. I have created a pull request with the plugin working correctly https://github.com/Significant-Gravitas/Auto-GPT-Plugins/pull/111. Best regards.
