### ISSUE TITLE
Error: No such option: --install-plugin-deps

### ISSUE THREAD

**Issue by hurrisonma** [Significant-Gravitas/Auto-GPT-Plugins#103]
~/Auto-GPT$./run.sh --install-plugin-deps
The command returns an error.
Error: No such option: --install-plugin-deps

**Comment by EticalPy** [comment]
Switch to the master branch:
git checkout master
git pull

**Comment by hurrisonma** [comment]
Switch to the master branch:
git checkout master
git pul

Problem solved.
