### ISSUE TITLE
Twitter changed their free API access this week and it now cost $100 a month to do anything but tweet, change needed?

### ISSUE THREAD

**Issue by smarshall561** [Significant-Gravitas/Auto-GPT-Plugins#117]
Supposedly you can still post tweet with the free API but I am getting this message for every function including post_tweet 

Command post_tweet returned: Error: 403 Forbidden 453 - You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve

Does something need to change in the code to still be able to send post tweets?

**Comment by Momof3disneyfans** [comment]
PLAN:
-  Use 'search_twitter_user' command to search for the user's Twitter account and ensure that we are using the correct Twitter handle
CRITICISM:  I need to make sure that we are using the correct Twitter handle and that the Twitter API connection is working properly.
NEXT ACTION:  COMMAND = search_twitter_user ARGUMENTS = {'target_user': '<user_handle>', 'number_of_tweets': 1}
SYSTEM:  Command search_twitter_user returned: Error: 403 Forbidden 453 - You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll
 need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve
 THOUGHTS:  We should use the 'list_agents' command to list the available GPT agents and see if there is an agent that can help us troubleshoot the issue with the Twitter API connection.
REASONING:  Using the 'list_agents' command to list the available GPT agents will help us see if there is an agent that can help us troubleshoot the issue with the Twitter API connection and provide us with guidance on how to resolve the issue.

**Comment by ntindle** [comment]
Feel free to contribute to the plugin but this isn't currently supported
