### ISSUE TITLE
Space plugin in main plugins repo has extremely vague description in readme. Does not link back to repo. improve documentation

### ISSUE THREAD

**Issue by smarshall561** [Significant-Gravitas/Auto-GPT-Plugins#147]
Space plugin hidden in main plugins repo, has extremely vague description in readme. Does not link back to repo. Malicious?

**Comment by smarshall561** [comment]
# Auto-GPT Space Plugin
This plugin enables AutoGPT to see how many people are in space. This can help enable AutoGPT to better achieve its goals

## Use cases
 - Researching how many people are in space
## Setup
Setup is easy. Just follow the instructions in [Auto-GPT-Plugins/README.md](https://github.com/Significant-Gravitas/Auto-GPT-Plugins/blob/master/README.md)

**Comment by ntindle** [comment]
No it just tells you the number of people in space

**Comment by smarshall561** [comment]
Why is there zero documentation?

**Comment by ntindle** [comment]
Also the readme got sorted and looks like it was left out by accident

**Comment by ntindle** [comment]
fixed
