### ISSUE TITLE
DENYLISTED_PLUGINS

### ISSUE THREAD

**Issue by solo2424** [Significant-Gravitas/Auto-GPT-Plugins#156]
I noticed recently as the addition of the DENYLISTED_PLUGINS. I assume this would allow you to deny plugins you do not wish to load. But when I add plugins to this list, the startup still prompts me to add them to the allowed list. Not sure if this is a bug or the intended result. But ideally, once a plugin is added to the denylisted, startup will no longer pester you about it. This is particularly important for first party plugins which are installed by default.

**Comment by monkeyden** [comment]
Are you using the stable version (v0.3.0) of Auto-GPT or master?  The DENYLISTED_PLUGINS is still only in master so not part of an official release yet.

**Comment by ntindle** [comment]
Resolved ^
