### ISSUE TITLE
Each action overwrote the same txt file instead of appending to the end of the file.

### ISSUE THREAD

**Issue by johnjac-cisco** [Significant-Gravitas/Auto-GPT-Plugins#178]
The task was to give a detailed explanation of something, and auto-gpt broke the task in to several "writing sections" but instead of appending each section to the text file, it over wrote each time
[activity.log](https://github.com/Significant-Gravitas/Auto-GPT-Plugins/files/11556444/activity.log)

**Comment by johnjac-cisco** [comment]
Sorry put issue in wrong place

**Comment by lc0rp** [comment]
Closing this. Please open in Auto-GPT repo
