### ISSUE TITLE
Which version of Telethon for Telgram?

### ISSUE THREAD

**Issue by monkeyden** [Significant-Gravitas/Auto-GPT-Plugins#181]
Trying to add the Telegram plugin and getting this error on startup:

```
TypeError: TelegramBaseClient.__init__() missing 3 required positional arguments: 'session', 'api_id', and 'api_hash'
Press any key to continue . . .
```
requirements.txt assumes latest.

I currently have:
Name: Telethon
Version: 1.28.5

**Comment by lc0rp** [comment]
It may help to ask in the telegram plugin thread here: https://discordapp.com/channels/1092243196446249134/1098744258791477248

**Comment by Wladastic** [comment]
The plugin is not using Telethon at all.
Please read the readme.
the requirements.txt only has the python telegram bot package.
