### ISSUE TITLE
[feature request]: I want you to write plugin link of google bard in the README.

### ISSUE THREAD

**Issue by RuiHirano** [Significant-Gravitas/Auto-GPT-Plugins#183]
I have implemented google bard plugin.
If there is no problem, I would like you to add it to the README.

https://github.com/RuiHirano/Auto-GPT-Bard-Plugin

**Comment by lc0rp** [comment]
Great! 

It's probably worth creating a thread in discord here to get some eyes on it/testers: https://discordapp.com/channels/1092243196446249134/1098737397094694922

And then, when ready, you can follow the instructions here to create a PR that adds this as a third-party plugin:
- https://github.com/Significant-Gravitas/Auto-GPT-Plugins#creating-a-plugin
