### ISSUE TITLE
Twitter Integration via tweepy

### ISSUE THREAD

**Issue by desojo** [Significant-Gravitas/Auto-GPT-Plugins#2]
Creation of a plugin that allows AutoGPT to interface with Twitter using tweepy

I have been messing around with twitter integration on [my own fork of AutoGPT](https://github.com/desojo/AutoGPTweeter/tree/feature_development)

So far, AutoGPTweeter has the ability to tweet out asking for tasks, check its mentions, and respond to mentions with a completed task. 

It's OK in its current state as a modification of base AutoGPT, but I think this would be better suited as a plugin

I'm excited to see future development and a potential for easy extensibility of AutoGPT, and I will be watching this repo closely

**Comment by ntindle** [comment]
Fixed by #7
