### ISSUE TITLE
Auto-GPT cant read javascript site

### ISSUE THREAD

**Issue by luanon404** [Significant-Gravitas/Auto-GPT-Plugins#20]
Some sites require JavaScript to load. For example: <script src="https://abc.com/xyz.js"></script>
They load the site by running the https://abc.com/xyz.js file. After 5 seconds, a picture of a cat will appear. However, auto-gpt can't wait for it and get a cat picture and only retrieves the raw response HTML: <script src="https://abc.com/xyz.js"></script>

**Comment by luanon404** [comment]
move from Auto-GPT Issues

**Comment by Pwuts** [comment]
Please be more specific what function you are calling etc

**Comment by luanon404** [comment]
> Please be more specific what function you are calling etc

For example, if you use https://temp-mail.org/en/, you need to wait 5 seconds for the mail to generate. However, the auto-gpt cannot wait and retrieves the source code before the mail appears, which means it cannot retrieve the mail.

**Comment by ntindle** [comment]
not a bug in plugins
