### ISSUE TITLE
Can't send a Tweet

### ISSUE THREAD

**Issue by pepeto** [Significant-Gravitas/Auto-GPT-Plugins#23]
I am using the stable version. I have followed all the instructions about the KEYS, I have the free access. Actually, I am using twitter with another app with no problem via the Bearer key.

I am still getting the 'reason' issue.

**SYSTEM:  Command send_tweet returned: Error: 'Unauthorized' object has no attribute 'reason'**
**REASONING:  Since there is no issue with my Twitter credentials, I can proceed with sending a tweet.**

Thank you!!! I love your work!

**Comment by ntindle** [comment]
I unfortunately don't have a twitter api key so I can't help :(

**Comment by jeffreycam** [comment]
the latest version of the twitter plugin wants this information added to the end of your env file. It has two additional tokens, Client ID & Client ID Secret.


################################################################################
### TWITTER API
################################################################################

# Consumer Keys are also known as API keys on the dev portal

TW_CONSUMER_KEY=
TW_CONSUMER_SECRET=
TW_ACCESS_TOKEN=
TW_ACCESS_TOKEN_SECRET=
**TW_CLIENT_ID=
TW_CLIENT_ID_SECRET=**

**Comment by ntindle** [comment]
@desojo

**Comment by monkeyden** [comment]
> the latest version of the twitter plugin wants this information added to the end of your env file. It has two additional tokens, Client ID & Client ID Secret.
> 
> ################################################################################
> 
> ### TWITTER API
> ################################################################################
> 
> # Consumer Keys are also known as API keys on the dev portal
> TW_CONSUMER_KEY= TW_CONSUMER_SECRET= TW_ACCESS_TOKEN= TW_ACCESS_TOKEN_SECRET= **TW_CLIENT_ID= TW_CLIENT_ID_SECRET=**

So what are the middle two (TW_ACCESS_TOKEN, TW_ACCESS_TOKEN_SECRET)?  The doc only mentions what Twitter calls "API Key" & "API Key Secret", and Twitter only shows those two in the Dev Portal.

**Comment by brk275** [comment]
Its a pain in the ass to get through the auth now but I figured it out
