### ISSUE TITLE
Add Baidu to search

### ISSUE THREAD

**Issue by youthhn** [Significant-Gravitas/Auto-GPT-Plugins#35]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

In different languages, the accessibility, content accuracy, and richness of different search engines vary, so it is recommended to increase support for Bing and Baidu

**Comment by ntindle** [comment]
Partially done, I can't include the Baidu plugin until we have an LLM provider that allows use within China. I expect progress on that soon

**Comment by ntindle** [comment]
Also will need to be provided an API key for testing and pipelines for this one, I'm pretty sure, as I don't have a Chinese phone number

**Comment by ForestLinSen** [comment]
> Also will need to be provided an API key for testing and pipelines for this one, I'm pretty sure, as I don't have a Chinese phone number

Actually they don't even provide search engine API, so for now the feasible way is to scrape the search result page with the user's own browser cookie

**Comment by ntindle** [comment]
Oof this one may be a bit of a challenge then

**Comment by youthhn** [comment]
> 哦，这个可能有点挑战

Considering joining Baidu is not just aimed at Chinese users, but can increase or improve access to Chinese materials. At present, this system is not very friendly to Chinese language requirements. And use Bing also can search  for content different from Google. So we can also try developing a search plugin for Bing. Gradually add search for Baidu when appropriate, and there are also many cases on Github
