### ISSUE TITLE
Zappier Connection

### ISSUE THREAD

**Issue by horazius** [Significant-Gravitas/Auto-GPT-Plugins#4]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

We need a Zappier Conntection to do so much more. We should give AutoGPT the possibility to write his own Zappier Connections as soon as we have on Zappier an existing AutoGPT-Extension. I guess this would bring a big boost into the topic. We just need before the cost thing done. Therefore we need a calculation schema.

### Motivation 🔦

To do so much more in a faster way.

**Comment by alreadydone** [comment]
I know about Zapier but not Za*pp*ier :)

**Comment by horazius** [comment]
Yes, true story. So Zapier at all.

**Comment by h4ck3rk3y** [comment]
Seems like we have this third party plugin listed - https://github.com/AntonioCiolino/AutoGPT-Zapier

I haven't tried using it yet though!
