### ISSUE TITLE
Email plugin - Unknown send email commands

### ISSUE THREAD

**Issue by JasperPeaches** [Significant-Gravitas/Auto-GPT-Plugins#41]
I have AutoGPT working except for the Plugins. Unknown commands trying to send emails. My guess is it does to recognize the plugins. I am using Windows and double checked all .env and file / folder configurations.

**Comment by ben-lovell** [comment]
Just adding a bump to this - I'm facing the same problem. I can get the Email Plugin to run on its own but not as a part of AutoGPT

**Comment by voska** [comment]
Same issue on Mac. I followed the instructions from the readme.

**Comment by zhound420** [comment]
Same here. Ubuntu linux. send_email is not allowed.

**Comment by Zeddi92** [comment]
Same problem here. Now it doesnt even try that commans

**Comment by ntindle** [comment]
@riensen any ideas?

**Comment by Zeddi92** [comment]
> @riensen any ideas?

I found the solution. The stable branch of auto-gpt does not support plugins yet. You have to pull the master branch (where the plugins folder exists). Then install the plugins as instructed and everything will work fine.
