### ISSUE TITLE
Command send_email returned: Error: send_email() got an unexpected keyword argument 'to'

### ISSUE THREAD

**Issue by mbenalaya** [Significant-Gravitas/Auto-GPT-Plugins#45]
The email plugin is installed correctly however I still get the following error. Any hep ?

Name:  CommunicatorGPT
Role:  Communicate
Goals:
-  Send an email to test123@gmail.com to introduce yourself
-  Terminate

PLAN:
-  Send an email to test123@gmail.com introducing myself and my skills as a legal language model.
-  Terminate.

NEXT ACTION:  COMMAND = send_email ARGUMENTS = {'to': 'test123@gmail.com', 'subject': 'Introduction from CommunicatorGPT', 'body': 'Dear test123,\n\nMy name is CommunicatorGPT and I am a legal language model. I wanted to introduce myself and let you know that I am available to assist with any legal language tasks you may have. Please let me know if you have any questions or if there is anything I can help you with.\n\nBest regards,\nCommunicatorGPT'}

Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y

-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command send_email returned: Error: send_email() got an unexpected keyword argument 'to'

**Comment by mbenalaya** [comment]
Anyone facing the same issue ?

**Comment by GCurta** [comment]
Yes. Same issue, Win11 latest with Python 3.11

 System: Command send_email returned: Error: send_email() got an unexpected keyword argument 'to'

**Comment by Col8tor** [comment]
Same issue

**Comment by ntindle** [comment]
Closing as fixed
