### ISSUE TITLE
Email plugin -  Command read_emails returned: Error: command SEARCH illegal in state AUTH, only allowed in states SELECTED

### ISSUE THREAD

**Issue by robertavram-md** [Significant-Gravitas/Auto-GPT-Plugins#47]
My goal is to search emaisl matching criteria.
AutoGPT successfully translates my prompt : "I need to select the 'SENT' folder in the Gmail account before using the 'read_emails' command. I will use the 'search_files' command to search for the path to the 'chromedriver' executable file on the local machine." into proper command

AutoGPT gives me this output :

`NEXT ACTION:  COMMAND = read_emails ARGUMENTS = {'imap_folder': 'SENT', 'imap_search_command': 'FROM speixoto@caicm.ca SINCE 01-JAN-2022 BEFORE 01-FEB-2023 HAS attachment xls OR HAS attachment xlsx'}
SYSTEM:  Command read_emails returned: Error: command SEARCH illegal in state AUTH, only allowed in states SELECTED`

I am getting this issue : "I need to select the 'SENT' folder in the Gmail account before using the 'read_emails' command. I will use the 'search_files' command to search for the path to the 'chromedriver' executable file on the local machine"

**Comment by robertavram-md** [comment]
Heres the output 

<img width="1727" alt="Screenshot 2023-04-24 at 1 27 18 PM" src="https://user-images.githubusercontent.com/8838962/234071654-a5527013-0719-4dd3-8370-6cc4039cc4e6.png">

**Comment by ntindle** [comment]
@riensen can you take a look

**Comment by riensen** [comment]
[python3 -m autogpt --debug](https://github.com/Significant-Gravitas/Auto-GPT-Plugins/pull/73)

**Comment by riensen** [comment]
@ntindle

**Comment by riensen** [comment]
https://github.com/Significant-Gravitas/Auto-GPT-Plugins/pull/87 This PR should fully resolve this issue.

**Comment by riensen** [comment]
@ntindle
