### ISSUE TITLE
How to use Python3 command "pip install " to install plugins ?

### ISSUE THREAD

**Issue by lixiuming1991** [Significant-Gravitas/Auto-GPT-Plugins#52]
- The environment is Python3 on my computer does not support the command of "---install-plugin-deps ". 
- How to use pip command to install "plugin-deps" ?

**Comment by ntindle** [comment]
unzip the folder and install the requirements.txt by hand and rezip it

**Comment by ntindle** [comment]
what doesn't work about it? unzipping isn't intended to be done by the end user
