### ISSUE TITLE
no ZIP file available

### ISSUE THREAD

**Issue by ctbritt** [Significant-Gravitas/Auto-GPT-Plugins#53]
when running this command: `curl -L -o ./plugins/Auto-GPT-Plugins.zip https://github.com/Significant-Gravitas/Auto-GPT-Plugins/archive/refs/heads/master.zip` as per the readme, I get a message that there's no file at `./plugins/Auto-GPT-Plugins.zip`

**Comment by lixiuming1991** [comment]
You can use this command:  git clone -b stable --single-branch https://github.com/Significant-Gravitas/Auto-GPT.git

**Comment by Zeddi92** [comment]
Having the same problem. @lixiuming1991 Your solution just pulls another instance of auto-gpt, right? I would like to pull only the plugins.

**Comment by Wethouder** [comment]
Same problem.

The solution @lixiuming1991 offering pulls the AUTO-GPT base

**Comment by Zeddi92** [comment]
Solved the problem: Use `mkdir plugins`, then `curl -L -o ./plugins/Auto-GPT-Plugins.zip https://github.com/Significant-Gravitas/Auto-GPT-Plugins/archive/refs/heads/master.zip`.

**Comment by Wethouder** [comment]
Thanks works for me

**Comment by lixiuming1991** [comment]
I have a new problem when installing the plugins: the environment is
Python3 on my Mac. Python3 does not support the option args “- -
install-plugin-deps ”.  Do you have the same problem?

Wethouder ***@***.***>于2023年4月26日 周三01:42写道：

**Comment by ntindle** [comment]
@lixiuming1991 remove the space between the dashes
