### ISSUE TITLE
No such option

### ISSUE THREAD

**Issue by sponi78** [Significant-Gravitas/Auto-GPT-Plugins#56]
when executing python -m autogpt --install-plugin-deps
i get error, no such option.

**Comment by risgupta** [comment]
Are you the repo release version or the latest version? Its available in the latest commit.

**Comment by jeffreycam** [comment]
I've followed EVERY instruction to the letter, but still receive this error.  It would also be helpful to see visual representation of the file hierarchy.  I use Windows, and my file structure is:

/Auto-GPT/auto-gpt  [this is my auto-gpt root]
/Auto-GPT/auto-gpt-plugins

in the auto-gpt folder, there is not a folder for plugins, and it fails at that point.
I tried creating a plugins folder inside /Auto-GPT/auto-gpt, but that didn't work either.

**Comment by ntindle** [comment]
Can you try these again from the root of your autogpt repo https://github.com/Significant-Gravitas/Auto-GPT-Plugins#installation

**Comment by jeffreycam** [comment]
I was able to get past this be re-loading the current auto-gpt code...

my problem now is, when running the following: .\run.bat
--install-plugin-deps
I receive this message:

*File
"plugins\Auto-GPT-Plugins.zip\Auto-GPT-Plugins-master\src\autogpt_plugins\twitter\__init__.py",
line 41, in __init__*
*AttributeError: module 'tweepy' has no attribute 'Stream'*

I have downloaded plugins and added them to the env file with all the keys
and codes.

I can't get Auto-GPT to load at all, it continues to give me the same
error, and won't start.

Please advise.

Warm regards,
Jeffrey Cleary

Amazing World Cruises
11966 Reedy Creek Dr #103
Orlando, FL 32836
M: (407) 498-5878
AmazingWorldCruises.com <https://amazingworldcruises.com/>
LetsGoTravelUS.com <https://letsgotravelus.com/>
Florida Seller of Travel Ref. No. ST15578
CST 2090937-50 – Washington UBID No. 603189022
Iowa Registered Agency No. 1202

**Comment by ntindle** [comment]
tweetpy updated like 5 minutes before you tried this and had a break. try doing the plugins setup again, sorry about that! we pinned the version
