### ISSUE TITLE
\twitter_init.py", line 41, in init AttributeError: module 'tweepy' has no attribute 'Stream

### ISSUE THREAD

**Issue by jeffreycam** [Significant-Gravitas/Auto-GPT-Plugins#60]
I have in stalled the latest auto-gpt and auto-gpt-plugins code as of this writing. I literally downloaded fresh code and followed all the instructions, but there seems to be an issue:

ERROR MESSAGE PREVENTING EXECUTION: 
File "plugins\Auto-GPT-Plugins.zip\Auto-GPT-Plugins-master\src\autogpt_plugins\twitter_init.py", line 41, in init
AttributeError: module 'tweepy' has no attribute 'Stream

This occurs when I attempt to issues the ./run command

**Comment by amarkules1** [comment]
I just ran into this as well. Likely you're using version 4.14.0 of tweepy, which got rid of that Stream class. Try version 4.13.0, `pip install tweepy==4.13.0`

**Comment by jeffreycam** [comment]
AWESOME! This fixed my issue.

**Comment by jeffreycam** [comment]
AWESOME! This fixed my issue.
