### ISSUE TITLE
using the email plugin

### ISSUE THREAD

**Issue by sponi78** [Significant-Gravitas/Auto-GPT-Plugins#65]
Hi,
it seems that auto gpt does not want to use the email plugin, i followed all the steps in the of installation, and the example.
Auto GPT always wants to use a credential...txt file.
Any hints?

**Comment by ntindle** [comment]
Are you using master or stable?

**Comment by sponi78** [comment]
which one should i use? I'm using stable

**Comment by ntindle** [comment]
plugins are not released to stable yet, but will be soonish

**Comment by sponi78** [comment]
I'm sorry, but this did not help.
