### ISSUE TITLE
send_email command is not found

### ISSUE THREAD

**Issue by rastrat** [Significant-Gravitas/Auto-GPT-Plugins#68]

**Comment by rastrat** [comment]
Welcome back!  Would you like me to return to being CommunicatorGPT?
Continue with the last settings?
Name:  CommunicatorGPT
Role:  Communicate
Goals: ['Send an email to my-email-plugin-test@trash-mail.com to introduce yourself using the send_email command', 'Terminate']
Continue (y/n): y
Using memory of type:  LocalCache
Using Browser:  chrome
 THOUGHTS:  I will start by introducing myself to the email address provided using the send_email command.
REASONING:  I want to start by completing the first goal in the list of goals provided. This will help me get
 started and give me a sense of accomplishment.
PLAN: 
-  Use the send_email command to introduce myself to the email address provided.
-  Terminate the program.
CRITICISM:  I should have checked if I have the necessary credentials to send an email before starting the task.
NEXT ACTION:  COMMAND = send_email ARGUMENTS = {'to': 'my-email-plugin-test@trash-mail.com', 'subject': 'Introduction', 'body': 'Hello, my name is CommunicatorGPT. I am an AI language model designed to communicate with humans. I am here to complete the task you have assigned me. Please let me know if you have any questions or concerns. Thank you.'}
SYSTEM:  Command send_email returned: Unknown command 'send_email'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.

**Comment by ntindle** [comment]
@riensen

**Comment by riensen** [comment]
Please run with autogpt with debug flag
`python3 -m autogpt --debug`

Then check if the send_email command is in the command list of the initial auto gpt prompt.

**Comment by rastrat** [comment]
autogpt tries to execute the send_email command but system says its an invalid command and says to reffer to commands list
@riensen

**Comment by rastrat** [comment]
@riensen i am working on master branch

**Comment by riensen** [comment]
> autogpt tries to execute the send_email command but system says its an invalid command and says to reffer to commands list @riensen

Yes, I understand that. I cannot reproduce this on my machine and no other users have reported this problem.
I can only recommend to:
- use the latest version of both repos (Auto-GPT and Auto-GPT-Plugins)
- Folllow the setup instruction closely
- If the problem persists, then run auto-gpt in debug mode and paste the entire initial output here (up to the first processing of the first command):
use `python3 -m autogpt --debug` to run in debug
