### ISSUE TITLE
AttributeError: module 'tweepy' has no attribute 'Stream'

### ISSUE THREAD

**Issue by katmai** [Significant-Gravitas/Auto-GPT-Plugins#79]
hi,
i'm getting this on the latest master.

File "plugins/Auto-GPT-Plugins.zip/Auto-GPT-Plugins-master/src/autogpt_plugins/twitter/__init__.py", line 48, in __init__
AttributeError: module 'tweepy' has no attribute 'Stream'

**Comment by lucasquinteiro** [comment]
I'm having the same issue

**Comment by ntindle** [comment]
There was an error with the twitter plug-in’s backing library. Reinstall the version specified in requirements.txt
