### ISSUE TITLE
Additional Plugins install - Issue

### ISSUE THREAD

**Issue by twajothi** [Significant-Gravitas/Auto-GPT-Plugins#82]
I am getting following error after i have added zip file in ./plugins. Is there something that i might be missing : 

/AutoGPT/Auto-GPT/autogpt/plugins.py", line 218, in scan_plugins
    zipped_module = zipped_package.load_module(str(module.parent))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen zipimport>", line 283, in load_module
  File "<frozen zipimport>", line 778, in _get_module_code
zipimport.ZipImportError: can't find module '__MACOSX/Auto-GPT-Telegram-Plugin-master/src/telegram_plugin'

**Comment by ntindle** [comment]
Please open this issue on @Wladastic ’s repo

**Comment by Wladastic** [comment]
This happens when zipping on macos and is a macos thing. 
use terminal for zip
