### ISSUE TITLE
News search never returns any results

### ISSUE THREAD

**Issue by kristoffernolgren** [Significant-Gravitas/Auto-GPT-Plugins#94]
I have only ever gotten this result on news-search:

`SYSTEM:  Command news_search returned: [[], [], [], [], [], []]
`

Here is an example query:

`NEXT ACTION:  COMMAND = news_search ARGUMENTS = {'query': 'stock market trends today'}
`

Running on osx using python3, have set up a news api key, happy to provide more info if it could be helpful. I've got some experience with debugging.

**Comment by scottyallen** [comment]
I'm seeing the same thing.

**Comment by ntindle** [comment]
Yeah would love if you took a look to see if all the futures are resolving correctly. I’ve only seen this once in an older version so thought it was fixed.

**Comment by ntindle** [comment]
@PalAditya

**Comment by levlevin** [comment]
I am seeing the same issue, running in docker

**Comment by ntindle** [comment]
fix in #109
